#-------------------------------
# General Site Settings

menu:
#- {name: 'Projects', url: '#'}
- {name: 'About', url: 'about/'}
- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'Contact', url: 'contact/'}

seo:
-  {description: 'Vitor Sudbrack personal page'}
-  {rel-author: 'https://twitter.com/vitorsudbrack'}
-  {rel-publisher: 'https://twitter.com/vitorsudbrack'}

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua:

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'


#-------------------------------
# Work Section

projects:
- {name: 'About me', folder: 'about', file: 'about/'}
- {name: 'Observat√≥rio Covid-19 BR', folder: 'obs', file: 'projects/obs.html'}
- {name: 'Project Three', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'Project Four', folder: 'proj-4', file: 'projects/proj-4.html'}
- {name: 'Project Five', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/vitorsudbrack'}
- {icon: 'facebook', link: 'https://www.facebook.com/vsudbrack'}
- {icon: 'instagram', link: 'https://www.instagram.com/v_sud/'}
- {icon: 'youtube', link: 'https://www.youtube.com/channel/UCNRrtOK8RIkds4VUFm04Ptw'}
- {icon: 'github', link: 'https://github.com/vsudbrack'}
- {icon: 'envelope', link: 'mailto:vitorsudbrack@gmail.com'} 

#--------------------------------- 'twitter' 'facebook' 'github' 
# 'pinterest' 'google-plus'  'linkedin' 'youtube'  'instagram' 
# 'dribbble' 'behance'  'soundcloud' 'vine'

